version: '3.9'
services:
  my-web:
    build: ${WEB_PATH_DOCKERFILE}
    networks:
      - my-net
    container_name: my-web
    restart: always
    environment:
      BACK_HOSTNAME: my-back
    ports:
      - "8080:8080"
    depends_on:
      - my-back
  my-back:
    build: ${BACK_PATH_DOCKERFILE}
    networks:
      - my-net
    container_name: my-back
    restart: always
    environment:
      DB_HOSTNAME: my-postgres
      DB_NAME: my-db
    depends_on:
      - my-postgres
  my-postgres:
    image: postgres:15.1-alpine
    networks:
      - my-net
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDARA: ${DB_PATH_POSTGRES}
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_POSTGRES}
networks:
  my-net:
    driver: bridge